export const theme = {
  colors: {
    cream: '#FFFAE3',
    creamDark: '#FFF4C8',
    primary: '#85AE7B',
    primaryDark: '#5C8A4C',
    primaryDeep: '#3E6433',
    primaryBg: '#D2DDC4',
    yellow: '#F5D962',
    yellowLight: '#FFFBDC',
    yellowPale: '#FFFAE3',
    surface: '#FFFFFF',
    surfaceWarm: '#FEFAE8',
    gray100: '#F5F5F0',
    gray200: '#EEEAE4',
    gray300: '#E0D9C4',
    gray400: '#C4C0B4',
    gray500: '#7A7A7A',
    text: '#3A3A3A',
    textSub: '#7A7A7A',
    textWhite: '#FFFFFF',
    danger: '#E05555',
    dangerBg: '#FFF0F0',
    success: '#27823A',
    successBg: '#EAF5EA',
    pinkSub: '#FFEFEF',
  },
  fonts: {
    title: "'Jua', sans-serif",
    body: "'Noto Sans KR', sans-serif",
    display: "'Black Han Sans', sans-serif",
    hand: "'Gamja Flower', cursive",
    serif: "'Hahmlet', serif",
  },
  radius: {
    cardLg: '24px',
    cardSm: '20px',
    btn: '18px',
    input: '18px',
    modal: '28px',
    nav: '24px',
    tag: '12px',
    pill: '9999px',
    circle: '50%',
  },
  shadow: {
    default: '0 4px 20px rgba(0, 0, 0, 0.08)',
    sm: '0 2px 8px rgba(0, 0, 0, 0.05)',
    inset: 'inset 0 4px 10px rgba(0, 0, 0, 0.05)',
  },
  spacing: {
    1: '8px',
    2: '16px',
    3: '24px',
    4: '32px',
    5: '40px',
    6: '48px',
  },
  transition: {
    default: '0.25s ease',
    fast: '0.15s ease',
    slow: '0.35s ease',
  },
  size: {
    btnHeight: '56px',
    btnHeightSm: '44px',
    inputHeight: '52px',
    headerHeight: '60px',
    navHeight: '64px',
  },
  icon: {
    sm: '20px',
    md: '24px',
    lg: '28px',
  }
};

export type ThemeType = typeof theme;
