let selectedCategory = '';
const expenseCategories = [{id:'food',name:'식비'},{id:'life',name:'생활'},{id:'transport',name:'교통'},{id:'culture',name:'문화'},{id:'etc',name:'기타'}];

document.addEventListener('DOMContentLoaded',()=>{initAmountInput();initCategorySelection();initMemoCounter();initSubmitAction();initExpenseModal();initBottomNav();initNotification();});

function initAmountInput(){const input=document.querySelector('#amount-input');if(!input)return;input.addEventListener('input',e=>{const clean=e.target.value.replace(/[^\d]/g,'');e.target.value=clean?Number(clean).toLocaleString('ko-KR'):'';});input.addEventListener('paste',e=>{const text=(e.clipboardData||window.clipboardData).getData('text');if(/[^\d]/.test(text))e.preventDefault();});}
function initCategorySelection(){const buttons=[...document.querySelectorAll('.category-btn')];buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(item=>{item.classList.remove('active');item.setAttribute('aria-pressed','false');});button.classList.add('active');button.setAttribute('aria-pressed','true');selectedCategory=button.dataset.category;}));}
function getCategoryName(id){return expenseCategories.find(category=>category.id===id)?.name||'미지정';}
function initMemoCounter(){const input=document.querySelector('#memo-input');const counter=document.querySelector('#char-counter');if(!input||!counter)return;input.addEventListener('input',()=>{if(input.value.length>100)input.value=input.value.slice(0,100);counter.textContent=`${input.value.length} / 100`;});}
function initSubmitAction(){const form=document.querySelector('#expense-form');if(!form)return;form.addEventListener('submit',event=>{event.preventDefault();const amountInput=document.querySelector('#amount-input');const memoInput=document.querySelector('#memo-input');const amountValue=amountInput?.value.replace(/[^\d]/g,'')||'';if(!amountValue||Number(amountValue)===0){window.alert('지출 금액을 입력해주세요!');amountInput?.focus();return;}if(!selectedCategory){window.alert('사용하신 카테고리를 선택해주세요!');return;}saveExpense(Number(amountValue),selectedCategory,memoInput?.value.trim()||'');});}
function saveExpense(amount,category,memo){const data={id:Date.now(),amount,category,categoryName:getCategoryName(category),memo,createdAt:new Date().toISOString()};localStorage.setItem('latestExpense',JSON.stringify(data));openExpenseModal();}
function initExpenseModal(){const modal=document.querySelector('#expense-success-modal');if(!modal)return;modal.querySelectorAll('[data-modal-close]').forEach(button=>button.addEventListener('click',closeExpenseModal));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)closeExpenseModal();});}
function openExpenseModal(){const modal=document.querySelector('#expense-success-modal');if(!modal)return;modal.hidden=false;document.body.classList.add('modal-open');modal.querySelector('.expense-modal-bubble')?.focus();}
function closeExpenseModal(){const modal=document.querySelector('#expense-success-modal');if(!modal)return;modal.hidden=true;document.body.classList.remove('modal-open');document.querySelector('#btn-submit')?.focus();}
function initBottomNav(){document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>{if(item.dataset.href){window.location.href=item.dataset.href;return;}document.querySelectorAll('.nav-item').forEach(nav=>{nav.classList.remove('active');nav.removeAttribute('aria-current');});item.classList.add('active');item.setAttribute('aria-current','page');}));}
function initNotification(){document.querySelector('#notification-btn')?.addEventListener('click',()=>window.alert('새로운 알림이 없습니다.'));}
